# Generated by Django 2.1 on 2018-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(max_length=100)),
                ('gift', models.CharField(max_length=100)),
            ],
        ),
    ]
